### ISSUE TITLE
Small typo in README

### ISSUE THREAD

**Issue by arosen93** [whitead/molcloud#1]
The example is `molcloud [smiles_file] [output_file] --width 10`. However, `output_file` is an optional argument with the `--output_file` flag rather than a required positional argument.

It might also be worth linking to the Pygraphviz install instructions to avoid confusion like discussed here: https://twitter.com/flyingchow/status/1543047603658448896.

**Comment by whitead** [comment]
Thanks! Fixed by 34fb12b4138da7a4a17e2dec5812ff614e457265
